TUTORIAL: Simulation and inference with the Barrier model

```{r}
library(INLA)
library(fields)
library(rgdal)
library(viridisLite)

set.seed(2016)
set.inla.seed = 2016
```


```{r}
# TUTORIAL: Simulation and inference with the Barrier model
# https://haakonbakkagit.github.io/btopic103.html
smalldist = 0.2
# - the width of the opening in the barrier
width = 0.5
# - The width/thickness of the barrier

local.square.polygon = function(xlim, ylim){
  # - output is a square
  xlim = range(xlim); ylim = range(ylim)
  corner1 = c(xlim[1], ylim[2])
  corner2 = c(xlim[2], ylim[1])
  poly = Polygon(rbind(corner1, c(corner1[1], corner2[2]), corner2, c(corner2[1], corner1[2]), corner1), hole = FALSE)
  return(SpatialPolygons(list(Polygons(list(poly), ID = runif(1)))))
}

poly1 = local.square.polygon(xlim=c(-1, 5-smalldist/2), 
                             ylim=5+width*c(-.5, .5))
poly2 = local.square.polygon(xlim=c(5+smalldist/2, 11), 
                             ylim=5+width*c(-.5, .5))
poly.original = SpatialPolygons(c(poly1@polygons, poly2@polygons))

plot(poly.original, main="Barrier area polygon")
```


```{r}
max.edge.length = 0.4
# - The coarseness of the finite element approximation
# - Corresponds to grid-square width in discretisations
# - - Except that finite element approximations are better
# - Should be compared to size of study area
# - Should be less than a fourth of the estimated (posterior) 
#   spatial range
# - Up to 8x computational time when you halve this value
loc1 = matrix(c(0,0, 10,0, 0,10, 10,10), 4, 2, byrow = T)
# - This defines the extent of the interior part of the mesh
# - In an application, if you want the mesh to depend on your 
#   data locations, you may use those locations instead
seg = inla.sp2segment(poly.original)
# - Transforms a SpatialPolygon to an "inla polygon"
mesh = inla.mesh.2d(loc=loc1, interior = seg, 
                    max.e = max.edge.length, offset=1)
# - The INLA mesh constructor, used for any INLA-SPDE model
tl = length(mesh$graph$tv[,1])
# - the number of triangles in the mesh
posTri = matrix(0, tl, 2)
for (t in 1:tl){
  temp = mesh$loc[mesh$graph$tv[t, ], ]
  posTri[t,] = colMeans(temp)[c(1,2)] 
}
posTri = SpatialPoints(posTri)
# - the positions of the triangle centres

barrier = over(poly.original, SpatialPoints(posTri), returnList=T)
# - checking which mesh triangles are inside the barrier area
barrier = unlist(barrier)
poly.barrier = inla.barrier.polygon(mesh, barrier.triangles = barrier)
# - the Barrier model's polygon
# - in most cases this should be the same as poly.original

plot(mesh, main="Mesh and Omega")
plot(poly.barrier, add=T, col='lightblue')
plot(mesh, add=T)
points(loc1)
```

```{r}
local.plot.field = function(field, ...){
  xlim = c(2, 8); ylim = xlim;
  proj = inla.mesh.projector(mesh, xlim = xlim, 
                             ylim = ylim, dims=c(300, 300))
  # - Can project from the mesh onto a 300x300 grid 
  #   for plots
  field.proj = inla.mesh.project(proj, field)
  # - Do the projection
  image.plot(list(x = proj$x, y=proj$y, z = field.proj), 
             xlim = xlim, ylim = ylim, col = plasma(17), ...)  
  # - Use image.plot to get nice colors and legend
}
print(mesh$n)
```

```{r}
barrier.model = inla.barrier.pcmatern(mesh, barrier.triangles = barrier, prior.range = c(1.44, 0.5), prior.sigma = c(0.7, 0.5), range.fraction = 0.1)
# - Set up the inla model, including the matrices for solving the SPDE
```

```{r}
range = 3
# - the spatial range parameter
Q = inla.rgeneric.q(barrier.model, "Q", theta = c(0, log(range)))
# - the precision matrix for fixed ranges
# - Q is a function of the hyperparameters theta = c( log(sigma), log(range1), log(range2),...)
```

```{r}
u = inla.qsample(n=1, Q=Q, seed = set.inla.seed)
## Warning in inla.qsample(n = 1, Q = Q, seed = set.inla.seed): Since
## 'seed!=0', parallel model is disabled and serial model is selected
u = u[ ,1]
# - access the first sample

local.plot.field(u, main="The true (simulated) spatial field")
plot(poly.barrier, add=T, col='grey')
```

STATIONARY MODEL EXAMPLE FOR LATER COMPARISONS

```{r}
num.try = 500 
# - try to sample this number of data locations
loc.try = matrix(runif(num.try*2, min=2, max=8), 
                         num.try, 2)
# - locations sampled inside the barrier will be removed 
#   in a few lines
temp = SpatialPoints(loc.try)
loc.ok = is.na(over(temp, poly.barrier))
# - only allow locations that are not inside the Barrier area
loc.data = loc.try[loc.ok, ]
A.data = inla.spde.make.A(mesh, loc.data)
# - the projector matrix required for any spatial model
# - this matrix can transform the field-defined-on-the-mesh 
#   to the field-defined-on-the-data-locations
c(dim(A.data), mesh$n, nrow(loc.data))

# - shows that the dimensions are correct
u.data = A.data %*% u
# - project the field from the finite element  
#   representation to the data locations
# Next we create the dataframe object.

df = data.frame(loc.data)
# - df is the dataframe used for modeling
names(df) = c('locx', 'locy')
sigma.u = 1
# - size of the random effect
# - feel free to change this value
sigma.epsilon = 0.2
# - size of the iid noise in the Gaussian likelihood
# - feel free to change this value
df$y = drop(sigma.u*u.data + sigma.epsilon*rnorm(nrow(df)))
# - sample observations with gaussian noise
```

from https://becarioprecario.bitbucket.io/spde-gitbook/ch-lcox.html

```{r}
library(spatstat)
win <- owin(c(0, 3), c(0, 3))
npix <- 300
spatstat.options(npixel = npix)
beta0 <- 3
exp(beta0) * diff(range(win$x)) * diff(range(win$y))
## [1] 180.8
```

```{r}
sigma2x <- 0.2
range <- 1.2
nu <- 1
```


```{r}
# library(RandomFields)
set.seed(1)
lg.s <- rLGCP('matern', beta0, var = sigma2x,
  scale = range / sqrt(8), nu = nu, win = win)

xy <- cbind(lg.s$x, lg.s$y)[, 2:1]
(n <- nrow(xy))
## [1] 217

Lam <- attr(lg.s, 'Lambda')
rf.s <- log(Lam$v)
summary(as.vector(rf.s))

```

```{r}
loc.d <- 3 * cbind(c(0, 1, 1, 0, 0), c(0, 0, 1, 1, 0))
mesh <- inla.mesh.2d(loc.domain = loc.d, offset = c(0.3, 1), 
  max.edge = c(0.3, 0.7), cutoff = 0.05)
nv <- mesh$n

spde <- inla.spde2.pcmatern(mesh = mesh,
  # PC-prior on range: P(practic.range < 0.05) = 0.01
  prior.range = c(0.05, 0.01),
  # PC-prior on sigma: P(sigma > 1) = 0.01
  prior.sigma = c(1, 0.01)) 

dmesh <- book.mesh.dual(mesh)

domain.polys <- Polygons(list(Polygon(loc.d)), '0')
domainSP <- SpatialPolygons(list(domain.polys))
```

```{r}
library(rgeos)
w <- sapply(1:length(dmesh), function(i) {
  if (gIntersects(dmesh[i, ], domainSP))
    return(gArea(gIntersection(dmesh[i, ], domainSP)))
  else return(0)
})

```

```{r}
y.pp <- rep(0:1, c(nv, n))
e.pp <- c(w, rep(0, n)) 
imat <- Diagonal(nv, rep(1, nv))
lmat <- inla.spde.make.A(mesh, xy)
A.pp <- rbind(imat, lmat)
stk.pp <- inla.stack(
  data = list(y = y.pp, e = e.pp), 
  A = list(1, A.pp),
  effects = list(list(b0 = rep(1, nv + n)), list(i = 1:nv)),
  tag = 'pp')
```

```{r}
pp.res <- inla(y ~ 0 + b0 + f(i, model = spde), 
  family = 'poisson', data = inla.stack.data(stk.pp), 
  control.predictor = list(A = inla.stack.A(stk.pp)), 
  E = inla.stack.data(stk.pp)$e)
pp.res$summary.hyperpar
summary(pp.res)
```


```{r}
dp <- xy
coop <- dp
  
  #Prediction data
Ap <- inla.spde.make.A(mesh, loc = coop)
A.pred <- rbind(imat, Ap)
  
stk.pred <- inla.stack(
    data = list(y = NA, e = 0),
    A = list(A.pred, 1),
    effects =list(list(i = 1:mesh$n), list(b0 = rep(1, nrow(dp)+nv))),
    tag = 'pred')

joint.stk <- inla.stack(stk.pp, stk.pred)
```

```{r}
pp.res <- inla(y ~ 0 + b0 + f(i, model = spde), 
  family = 'poisson', data = inla.stack.data(stk.pp), 
  control.predictor = list(A = inla.stack.A(stk.pp)), 
  E = inla.stack.data(stk.pp)$e)
pp.res$summary.hyperpar
```


#####################
```{r}
book.mesh.dual <- function(mesh) {
    if (mesh$manifold=='R2') {
        ce <- t(sapply(1:nrow(mesh$graph$tv), function(i)
            colMeans(mesh$loc[mesh$graph$tv[i, ], 1:2])))
        library(parallel)
        pls <- mclapply(1:mesh$n, function(i) {
            p <- unique(Reduce('rbind', lapply(1:3, function(k) {
                j <- which(mesh$graph$tv[,k]==i)
                if (length(j)>0) 
                    return(rbind(ce[j, , drop=FALSE],
                                 cbind(mesh$loc[mesh$graph$tv[j, k], 1] +
                                       mesh$loc[mesh$graph$tv[j, c(2:3,1)[k]], 1], 
                                       mesh$loc[mesh$graph$tv[j, k], 2] +
                                       mesh$loc[mesh$graph$tv[j, c(2:3,1)[k]], 2])/2))
                else return(ce[j, , drop=FALSE])
            })))
            j1 <- which(mesh$segm$bnd$idx[,1]==i)
            j2 <- which(mesh$segm$bnd$idx[,2]==i)
            if ((length(j1)>0) | (length(j2)>0)) {
                p <- unique(rbind(mesh$loc[i, 1:2], p,
                                  mesh$loc[mesh$segm$bnd$idx[j1, 1], 1:2]/2 +
                                  mesh$loc[mesh$segm$bnd$idx[j1, 2], 1:2]/2, 
                                  mesh$loc[mesh$segm$bnd$idx[j2, 1], 1:2]/2 +
                                  mesh$loc[mesh$segm$bnd$idx[j2, 2], 1:2]/2))
                yy <- p[,2]-mean(p[,2])/2-mesh$loc[i, 2]/2
                xx <- p[,1]-mean(p[,1])/2-mesh$loc[i, 1]/2
            }
            else {
                yy <- p[,2]-mesh$loc[i, 2]
                xx <- p[,1]-mesh$loc[i, 1]
            }
            Polygon(p[order(atan2(yy,xx)), ])
        })
        return(SpatialPolygons(lapply(1:mesh$n, function(i)
            Polygons(list(pls[[i]]), i))))
    }
    else stop("It only works for R2!")
}

```

TUTORIAL THE BARRIER MODEL. SECTION 5

https://becarioprecario.bitbucket.io/spde-gitbook/ch-nonstationarity.html#ch:barrier

```{r}
# Select region 
map <- map("world", "Canada", fill = TRUE,
  col = "transparent", plot = FALSE)
IDs <- sapply(strsplit(map$names, ":"), function(x) x[1])
map.sp <- map2SpatialPolygons(
  map, IDs = IDs,
  proj4string = CRS("+proj=longlat +datum=WGS84"))
```


```{r}
# Select region 
map <- map("world", "Canada", fill = TRUE,
  col = "transparent", plot = FALSE)
IDs <- sapply(strsplit(map$names, ":"), function(x) x[1])
map.sp <- map2SpatialPolygons(
  map, IDs = IDs,
  proj4string = CRS("+proj=longlat +datum=WGS84"))
```

```{r}
pl.sel <- SpatialPolygons(list(Polygons(list(Polygon(
  cbind(c(-69, -62.2, -57, -57, -69, -69), 
    c(47.8, 45.2, 49.2, 52, 52, 48)),
     FALSE)), '0')), proj4string = CRS(proj4string(map.sp)))

poly.water <- gDifference(pl.sel, map.sp)
```

```{r}
# Define UTM projection
kmproj <- CRS("+proj=utm +zone=20 ellps=WGS84 +units=km")
# Project data
poly.water = spTransform(poly.water, kmproj)
pl.sel = spTransform(pl.sel, kmproj)
map.sp = spTransform(map.sp, kmproj)
```

```{r}
mesh.not <- inla.mesh.2d(boundary = poly.water, max.edge = 30,
  cutoff = 2)
```

```{r}
max.edge = 30
bound.outer = 150
mesh <- inla.mesh.2d(boundary = poly.water,
  max.edge = c(1,5) * max.edge,
  cutoff = 2,
  offset = c(max.edge, bound.outer))
```

```{r}
water.tri = inla.over_sp_mesh(poly.water, y = mesh, 
  type = "centroid", ignore.CRS = TRUE)
num.tri = length(mesh$graph$tv[, 1])
barrier.tri = setdiff(1:num.tri, water.tri)
poly.barrier = inla.barrier.polygon(mesh, 
  barrier.triangles = barrier.tri)
```

```{r}
range <- 200
barrier.model <- inla.barrier.pcmatern(mesh, 
  barrier.triangles = barrier.tri)
Q <- inla.rgeneric.q(barrier.model, "Q", theta = c(0, log(range)))
```

```{r}
stationary.model <- inla.spde2.pcmatern(mesh, 
  prior.range = c(1, 0.1), prior.sigma = c(1, 0.1))
Q.stat <- inla.spde2.precision(stationary.model, 
  theta = c(log(range), 0))
```

```{r}
# The location we find the correlation with respect to
loc.corr <- c(500, 5420)
corr <- book.spatial.correlation(Q, loc = loc.corr, mesh)
corr.stat <- book.spatial.correlation(Q.stat, loc = loc.corr,
  mesh)
```

```{r}
set.seed(201805)
loc.data <- spsample(poly.water, n = 1000, type = "random")
loc.data <- loc.data@coords
```

```{r}
# Seed is the month the code was first written times some number
u <- inla.qsample(n = 1, Q = Q, seed = 201805 * 3)[, 1]
A.data <- inla.spde.make.A(mesh, loc.data)
u.data <- A.data %*% u

# df is the dataframe used for modeling
df <- data.frame(loc.data)
names(df) <- c('locx', 'locy')
# Size of the spatial signal
sigma.u <- 1
# Size of the measurement noise
sigma.epsilon <- 0.1
df$y <- drop(sigma.u * u.data + sigma.epsilon * rnorm(nrow(df)))
```

```{r}
stk <- inla.stack(
  data = list(y = df$y),
  A = list(A.data, 1),
  effects =list(s = 1:mesh$n, intercept = rep(1, nrow(df))),
  tag = 'est')

form.barrier <- y ~ 0 + intercept + f(s, model = barrier.model)

res.barrier <- inla(form.barrier, data = inla.stack.data(stk),
  control.predictor = list(A = inla.stack.A(stk)),
  family = 'gaussian', 
  control.inla = list(int.strategy = "eb"))
```

```{r}
res.barrier$summary.hyperpar
##                                            mean     sd
## Precision for the Gaussian observations 94.4892 6.5776
## Theta1 for s                            -0.1348 0.1182
## Theta2 for s                             5.1357 0.1379
##                                         0.025quant 0.5quant
## Precision for the Gaussian observations    82.0188  94.3386
## Theta1 for s                               -0.3381  -0.1457
## Theta2 for s                                4.8992   5.1229
##                                         0.975quant    mode
## Precision for the Gaussian observations   107.8866 94.1400
## Theta1 for s                                0.1218 -0.1861
## Theta2 for s                                5.4352  5.0749
```
















